// Danh sách địa điểm trên thế giới cho travel expense

export const destinations = [
    // Việt Nam (Trong nước)
    { value: 'Hà Nội, Việt Nam', label: 'Hà Nội, Việt Nam', type: 'domestic', continent: null },
    { value: 'TP.HCM, Việt Nam', label: 'TP.HCM, Việt Nam', type: 'domestic', continent: null },
    { value: 'Hồ Chí Minh, Việt Nam', label: 'Hồ Chí Minh, Việt Nam', type: 'domestic', continent: null },
    { value: 'Đà Nẵng, Việt Nam', label: 'Đà Nẵng, Việt Nam', type: 'domestic', continent: null },
    { value: 'Hải Phòng, Việt Nam', label: 'Hải Phòng, Việt Nam', type: 'domestic', continent: null },
    { value: 'Cần Thơ, Việt Nam', label: 'Cần Thơ, Việt Nam', type: 'domestic', continent: null },
    { value: 'Dung Quất → Bình Sơn, Quảng Ngãi', label: 'Dung Quất → Bình Sơn, Quảng Ngãi', type: 'domestic', continent: null },
    { value: 'KCN Chu Lai → Núi Thành, Đà Nẵng', label: 'KCN Chu Lai → Núi Thành, Đà Nẵng', type: 'domestic', continent: null },
    { value: 'KCN Tam Thăng → Tam Kỳ, Đà Nẵng', label: 'KCN Tam Thăng → Tam Kỳ, Đà Nẵng', type: 'domestic', continent: null },
    { value: 'KCN Điện Ngọc → Điện Bàn, Đà Nẵng', label: 'KCN Điện Ngọc → Điện Bàn, Đà Nẵng', type: 'domestic', continent: null },
    { value: 'KCN Hòa Khánh → Liên Chiểu, Đà Nẵng', label: 'KCN Hòa Khánh → Liên Chiểu, Đà Nẵng', type: 'domestic', continent: null },
    { value: 'KCN Hòa Cầm → Cẩm Lệ, Đà Nẵng', label: 'KCN Hòa Cầm → Cẩm Lệ, Đà Nẵng', type: 'domestic', continent: null },
    { value: 'KCN Cao Đồn → Biên Hòa, Đồng Nai', label: 'KCN Cao Đồn → Biên Hòa, Đồng Nai', type: 'domestic', continent: null },
    { value: 'KCN An Phú → Tuy Hòa, Phú Yên', label: 'KCN An Phú → Tuy Hòa, Phú Yên', type: 'domestic', continent: null },

    // Châu Á
    { value: 'Singapore, Singapore', label: 'Singapore, Singapore', type: 'international', continent: 'ASIAN' },
    { value: 'Bangkok, Thái Lan', label: 'Bangkok, Thái Lan', type: 'international', continent: 'ASIAN' },
    { value: 'Jakarta, Indonesia', label: 'Jakarta, Indonesia', type: 'international', continent: 'ASIAN' },
    { value: 'Manila, Philippines', label: 'Manila, Philippines', type: 'international', continent: 'ASIAN' },
    { value: 'Kuala Lumpur, Malaysia', label: 'Kuala Lumpur, Malaysia', type: 'international', continent: 'ASIAN' },
    { value: 'Tokyo, Nhật Bản', label: 'Tokyo, Nhật Bản', type: 'international', continent: 'ASIAN' },
    { value: 'Seoul, Hàn Quốc', label: 'Seoul, Hàn Quốc', type: 'international', continent: 'ASIAN' },
    { value: 'Beijing, Trung Quốc', label: 'Beijing, Trung Quốc', type: 'international', continent: 'ASIAN' },
    { value: 'Shanghai, Trung Quốc', label: 'Shanghai, Trung Quốc', type: 'international', continent: 'ASIAN' },
    { value: 'Hong Kong, Trung Quốc', label: 'Hong Kong, Trung Quốc', type: 'international', continent: 'ASIAN' },
    { value: 'Taipei, Đài Loan', label: 'Taipei, Đài Loan', type: 'international', continent: 'ASIAN' },
    { value: 'New Delhi, Ấn Độ', label: 'New Delhi, Ấn Độ', type: 'international', continent: 'ASIAN' },
    { value: 'Mumbai, Ấn Độ', label: 'Mumbai, Ấn Độ', type: 'international', continent: 'ASIAN' },
    { value: 'Bangalore, Ấn Độ', label: 'Bangalore, Ấn Độ', type: 'international', continent: 'ASIAN' },
    { value: 'Dhaka, Bangladesh', label: 'Dhaka, Bangladesh', type: 'international', continent: 'ASIAN' },
    { value: 'Colombo, Sri Lanka', label: 'Colombo, Sri Lanka', type: 'international', continent: 'ASIAN' },
    { value: 'Kathmandu, Nepal', label: 'Kathmandu, Nepal', type: 'international', continent: 'ASIAN' },
    { value: 'Islamabad, Pakistan', label: 'Islamabad, Pakistan', type: 'international', continent: 'ASIAN' },
    { value: 'Karachi, Pakistan', label: 'Karachi, Pakistan', type: 'international', continent: 'ASIAN' },

    // Trung Đông
    { value: 'Dubai, UAE', label: 'Dubai, UAE', type: 'international', continent: 'ASIAN' },
    { value: 'Abu Dhabi, UAE', label: 'Abu Dhabi, UAE', type: 'international', continent: 'ASIAN' },
    { value: 'Doha, Qatar', label: 'Doha, Qatar', type: 'international', continent: 'ASIAN' },
    { value: 'Riyadh, Saudi Arabia', label: 'Riyadh, Saudi Arabia', type: 'international', continent: 'ASIAN' },
    { value: 'Kuwait City, Kuwait', label: 'Kuwait City, Kuwait', type: 'international', continent: 'ASIAN' },
    { value: 'Tehran, Iran', label: 'Tehran, Iran', type: 'international', continent: 'ASIAN' },
    { value: 'Tel Aviv, Israel', label: 'Tel Aviv, Israel', type: 'international', continent: 'ASIAN' },
    { value: 'Istanbul, Thổ Nhĩ Kỳ', label: 'Istanbul, Thổ Nhĩ Kỳ', type: 'international', continent: 'EU' },
    { value: 'Ankara, Thổ Nhĩ Kỳ', label: 'Ankara, Thổ Nhĩ Kỳ', type: 'international', continent: 'EU' },

    // Châu Âu
    { value: 'London, Anh', label: 'London, Anh', type: 'international', continent: 'EU' },
    { value: 'Paris, Pháp', label: 'Paris, Pháp', type: 'international', continent: 'EU' },
    { value: 'Berlin, Đức', label: 'Berlin, Đức', type: 'international', continent: 'EU' },
    { value: 'Frankfurt, Đức', label: 'Frankfurt, Đức', type: 'international', continent: 'EU' },
    { value: 'Munich, Đức', label: 'Munich, Đức', type: 'international', continent: 'EU' },
    { value: 'Madrid, Tây Ban Nha', label: 'Madrid, Tây Ban Nha', type: 'international', continent: 'EU' },
    { value: 'Barcelona, Tây Ban Nha', label: 'Barcelona, Tây Ban Nha', type: 'international', continent: 'EU' },
    { value: 'Rome, Ý', label: 'Rome, Ý', type: 'international', continent: 'EU' },
    { value: 'Milan, Ý', label: 'Milan, Ý', type: 'international', continent: 'EU' },
    { value: 'Amsterdam, Hà Lan', label: 'Amsterdam, Hà Lan', type: 'international', continent: 'EU' },
    { value: 'Brussels, Bỉ', label: 'Brussels, Bỉ', type: 'international', continent: 'EU' },
    { value: 'Vienna, Áo', label: 'Vienna, Áo', type: 'international', continent: 'EU' },
    { value: 'Stockholm, Thụy Điển', label: 'Stockholm, Thụy Điển', type: 'international', continent: 'EU' },
    { value: 'Copenhagen, Đan Mạch', label: 'Copenhagen, Đan Mạch', type: 'international', continent: 'EU' },
    { value: 'Oslo, Na Uy', label: 'Oslo, Na Uy', type: 'international', continent: 'EU' },
    { value: 'Helsinki, Phần Lan', label: 'Helsinki, Phần Lan', type: 'international', continent: 'EU' },
    { value: 'Dublin, Ireland', label: 'Dublin, Ireland', type: 'international', continent: 'EU' },
    { value: 'Lisbon, Bồ Đào Nha', label: 'Lisbon, Bồ Đào Nha', type: 'international', continent: 'EU' },
    { value: 'Warsaw, Ba Lan', label: 'Warsaw, Ba Lan', type: 'international', continent: 'EU' },
    { value: 'Prague, Cộng hòa Séc', label: 'Prague, Cộng hòa Séc', type: 'international', continent: 'EU' },
    { value: 'Budapest, Hungary', label: 'Budapest, Hungary', type: 'international', continent: 'EU' },
    { value: 'Athens, Hy Lạp', label: 'Athens, Hy Lạp', type: 'international', continent: 'EU' },
    { value: 'Zurich, Thụy Sĩ', label: 'Zurich, Thụy Sĩ', type: 'international', continent: 'EU' },
    { value: 'Geneva, Thụy Sĩ', label: 'Geneva, Thụy Sĩ', type: 'international', continent: 'EU' },
    { value: 'Reykjavik, Iceland', label: 'Reykjavik, Iceland', type: 'international', continent: 'EU' },
    { value: 'Moscow, Nga', label: 'Moscow, Nga', type: 'international', continent: 'EU' },
    { value: 'Saint Petersburg, Nga', label: 'Saint Petersburg, Nga', type: 'international', continent: 'EU' },

    // Châu Mỹ
    { value: 'New York, USA', label: 'New York, USA', type: 'international', continent: 'AMERICAS' },
    { value: 'Los Angeles, USA', label: 'Los Angeles, USA', type: 'international', continent: 'AMERICAS' },
    { value: 'Chicago, USA', label: 'Chicago, USA', type: 'international', continent: 'AMERICAS' },
    { value: 'San Francisco, USA', label: 'San Francisco, USA', type: 'international', continent: 'AMERICAS' },
    { value: 'Washington D.C., USA', label: 'Washington D.C., USA', type: 'international', continent: 'AMERICAS' },
    { value: 'Boston, USA', label: 'Boston, USA', type: 'international', continent: 'AMERICAS' },
    { value: 'Miami, USA', label: 'Miami, USA', type: 'international', continent: 'AMERICAS' },
    { value: 'Toronto, Canada', label: 'Toronto, Canada', type: 'international', continent: 'AMERICAS' },
    { value: 'Vancouver, Canada', label: 'Vancouver, Canada', type: 'international', continent: 'AMERICAS' },
    { value: 'Montreal, Canada', label: 'Montreal, Canada', type: 'international', continent: 'AMERICAS' },
    { value: 'Mexico City, Mexico', label: 'Mexico City, Mexico', type: 'international', continent: 'AMERICAS' },
    { value: 'São Paulo, Brazil', label: 'São Paulo, Brazil', type: 'international', continent: 'AMERICAS' },
    { value: 'Rio de Janeiro, Brazil', label: 'Rio de Janeiro, Brazil', type: 'international', continent: 'AMERICAS' },
    { value: 'Buenos Aires, Argentina', label: 'Buenos Aires, Argentina', type: 'international', continent: 'AMERICAS' },
    { value: 'Santiago, Chile', label: 'Santiago, Chile', type: 'international', continent: 'AMERICAS' },

    // Châu Úc
    { value: 'Sydney, Australia', label: 'Sydney, Australia', type: 'international', continent: 'OCEANIA' },
    { value: 'Melbourne, Australia', label: 'Melbourne, Australia', type: 'international', continent: 'OCEANIA' },
    { value: 'Brisbane, Australia', label: 'Brisbane, Australia', type: 'international', continent: 'OCEANIA' },
    { value: 'Perth, Australia', label: 'Perth, Australia', type: 'international', continent: 'OCEANIA' },
    { value: 'Auckland, New Zealand', label: 'Auckland, New Zealand', type: 'international', continent: 'OCEANIA' },
    { value: 'Wellington, New Zealand', label: 'Wellington, New Zealand', type: 'international', continent: 'OCEANIA' },

    // Châu Phi
    { value: 'Cairo, Ai Cập', label: 'Cairo, Ai Cập', type: 'international', continent: 'AFRICA' },
    { value: 'Johannesburg, Nam Phi', label: 'Johannesburg, Nam Phi', type: 'international', continent: 'AFRICA' },
    { value: 'Cape Town, Nam Phi', label: 'Cape Town, Nam Phi', type: 'international', continent: 'AFRICA' },
    { value: 'Nairobi, Kenya', label: 'Nairobi, Kenya', type: 'international', continent: 'AFRICA' },
];


